'use strict';
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const required = ['index.html', 'assets/style.css', 'assets/app.source.js', 'data/parcels.json', 'data/generated/flood.pmtiles', 'data/generated/soils.pmtiles', 'data/generated/huc12.pmtiles', 'data/generated/railroads.pmtiles', 'scripts/refresh-data.js'];
const failures = required.filter(file => !fs.existsSync(path.join(root, file)));
if (!failures.length) {
  const data = JSON.parse(fs.readFileSync(path.join(root, 'data/parcels.json')));
  if (data.type !== 'FeatureCollection') failures.push('data/parcels.json is not GeoJSON');
  if (!Array.isArray(data.features) || !data.features.length) failures.push('data/parcels.json has no parcel features');
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  const app = fs.readFileSync(path.join(root, 'assets/app.source.js'), 'utf8');
  const listings = fs.readFileSync(path.join(root, 'assets/data/listings.js'), 'utf8');
  const parcelDetails = fs.readFileSync(path.join(root, 'assets/ui/parcel-details.js'), 'utf8');
  const mapLayers = fs.readFileSync(path.join(root, 'assets/map/layers.js'), 'utf8');
  const urlState = fs.readFileSync(path.join(root, 'assets/state/url.js'), 'utf8');
  if (!listings.includes('separatedUnmappedListings') || !listings.includes('separatedCoordinate') || !listings.includes('const radiusFeet = 100')) failures.push('Coincident unmapped MLS dots are not separated by a fixed geographic distance');
  const refresh = fs.readFileSync(path.join(root, 'scripts/refresh-data.js'), 'utf8');
  if (!refresh.includes('const UNRESOLVED_LISTING_FALLBACK = [41.328436, -122.326324]') || !refresh.includes("locationSource: 'City Park fallback (listing location unresolved)'") || !refresh.includes("record.category = ['land', 'farm'].includes(record.propertyType)") || !refresh.includes('unmapped.push(record);')) failures.push('Locationless MLS listings are not retained at the City Park fallback');
  if (!refresh.includes('async function countyStreetPoint(item)') || !refresh.includes('async function countyRoadPoint(item)') || !refresh.includes("'county road centerline (approximate)'") || !refresh.includes('preferredUnmappedLocation(item, mlsLatLng, streetPoints[index])')) failures.push('Locationless street listings are not placed using county streets or roads');
  if (!refresh.includes("UPPER(MSAGComm) = '${city}'") || !refresh.includes('Retry by advertised town whenever')) failures.push('Exact addresses with mistyped ZIPs do not fall back to their town');
  if (!refresh.includes('async function countyRegionPlacement(item, cache)') || !refresh.includes("'county ZIP/town street match (approximate)'") || !refresh.includes("'ZIP code centroid (approximate)'") || !refresh.includes('const regionCache = new Map()')) failures.push('Right-to-left ZIP, town, and street placement is missing');
  if (!refresh.includes('/^\\s*(?:PAR(?:CEL)?|PRCL)\\.?\\s*#?\\s*[\\dA-Z-]+\\s+/')) failures.push('Parcel-number street prefixes such as Par. 3 are not stripped');
  if (!refresh.includes('/\\b(?:LOTS?|BLOCKS?)\\s*[#-]?\\s*\\d+/i')) failures.push('Plural Lots listings are missing from the parcel review queue');
  if (!html.includes('Find an APN, address, listing, or place') || !listings.includes('recordMatchesSearch') || !listings.includes('filteredMappedListings') || !listings.includes('filteredUnmappedListings') || !app.includes("addEventListener('search', findListings)")) failures.push('Expanded address, listing, and place search is missing');
  if (!html.includes('id="minimum-acreage"') || !html.includes('max="100" step="1"') || !app.includes('minimumAcreage = Number(minimumAcreageInput.value)') || !app.includes("minimumAcreageInput.addEventListener('input'") || !listings.includes('recordIsVisible')) failures.push('Granular 0–100 minimum acreage filter is missing');
  if (!html.includes('id="listed-since" type="date"') || !listings.includes('recordMatchesListingDate') || !app.includes("listedSinceInput.addEventListener('change'")) failures.push('Listed-since date filter is missing');
  if (!html.includes('parcelquest-warning')) failures.push('ParcelQuest warning dialog is missing');
  if (!parcelDetails.includes('Look up owner & assessment') || !parcelDetails.includes('Siskiyou County Assessor')) failures.push('County owner lookup action is missing');
  if (!parcelDetails.includes('salesHistorySection') || !parcelDetails.includes('No matched public sold-listing history')) failures.push('Clicked parcels do not display sales history');
  if (!refresh.includes("fetchMls('homes-sold')") || !refresh.includes("kind: 'sale-history'") || !refresh.includes('feature.properties.salesHistory = salesHistory')) failures.push('Sold MLS history is not ingested by APN');
  if (!refresh.includes("'mls-apn-links.json'") || !refresh.includes('function saveMlsLinks(') || !refresh.includes('persisted MLS linkage:') || !refresh.includes('overrideApns[0] || listedApn || persistedApns[0]')) failures.push('MLS-to-APN linkages are not persisted and reused');
  if (!app.includes("const DIRECTIONS_ORIGIN = 'Mt. Shasta City Park") || !parcelDetails.includes("new URL('https://www.google.com/maps/dir/')") || !parcelDetails.includes('destination: `${point[1]},${point[0]}`') || !parcelDetails.includes('Directions from Mt. Shasta City Park')) failures.push('Parcel directions from Mt. Shasta City Park are missing');
  if (!app.includes('localStorage')) failures.push('browser-local research cache is missing');
  if (!mapLayers.includes("id: 'road-labels'") || !mapLayers.includes("['get', 'ROADNAME']")) failures.push('County road name labels are missing');
  if (!app.includes("roads: ['roads', 'road-labels', 'forest-roads', 'forest-road-labels']")) failures.push('Road toggle does not control county and USFS road layers');
  if (!html.includes('data-map-layer="railroads"')) failures.push('Railroad toggle is missing');
  if (!app.includes("railroads: ['railroad-casing', 'railroads', 'railroad-ties', 'railroad-labels']")) failures.push('Railroad toggle does not control all railroad layers');
  if (!html.includes('data-map-layer="huc12"')) failures.push('HUC-12 watershed toggle is missing');
  if (!app.includes("huc12: ['huc12-fill', 'huc12-lines', 'huc12-labels']") || !mapLayers.includes("'source-layer': 'huc12'")) failures.push('HUC-12 watershed layers are missing');
  if (!mapLayers.includes("'line-color': '#e53935'") || !mapLayers.includes("['get', 'SUBDIV']")) failures.push('Railroad styling or labels are missing');
  if (!app.includes("const TERRAIN_URL_PARAM = 'terrain'") || !urlState.includes("url.searchParams.set(name, value)") || !app.includes("applyTerrain(true, { updateUrl: false, animate: false })")) failures.push('3D terrain mode is not persisted in the URL');
  if (!parcelDetails.includes("target.textContent = ` · ${zoning") || parcelDetails.includes('Land use ${escapeHtml(p.LandUse1)')) failures.push('Parcel details do not replace numeric land use with zoning');
  if (!app.includes("const PARCEL_URL_PARAM = 'parcel'") || !app.includes('updateUrlParameter(PARCEL_URL_PARAM, apn)') || !app.includes('restoreInitialSelectedParcel()')) failures.push('Selected parcel is not persisted in the URL');
  if (!app.includes("url.searchParams.set('v', new URL(import.meta.url).pathname.split('/').pop())")) failures.push('PMTiles URLs are not versioned by the application bundle');
  const controls = fs.readFileSync(path.join(root, 'assets/map/controls.js'), 'utf8');
  if (!controls.includes('class MilesScaleControl') || !controls.includes("this.container.textContent = `${Number(niceMiles.toPrecision(3))} mi`")) failures.push('Miles-only map distance scale is missing');
  if (!controls.includes('formatBearing(start, end)') || !controls.includes('${northSouth} ${degrees}°')) failures.push('Measure tool does not display a plat-style bearing');
  if (!controls.includes('class CoordinatePinControl') || !controls.includes('www.google.com/maps/search/?api=1&query=') || !mapLayers.includes("map.addSource('coordinate-pin'")) failures.push('Coordinate pin with Google Maps link is missing');
  const vite = fs.readFileSync(path.join(root, 'vite.config.mjs'), 'utf8');
  for (const worker of ['maplibre-gl-worker.mjs', 'maplibre-gl-shared.mjs']) if (!vite.includes(worker)) failures.push(`production worker asset is missing: ${worker}`);
  if (!app.includes("...(id === 'parcels' ? { promoteId: 'APN' } : {})")) failures.push('Parcel APNs are not promoted to feature IDs');
  if (!mapLayers.includes("['feature-state', 'selected']") || !app.includes("map.setFeatureState({ source: 'parcels', sourceLayer: 'parcels', id: selectedApn }")) failures.push('Parcel selection does not use feature state');
  if (app.includes("map.setFilter('parcel-selected'")) failures.push('Parcel selection still rebuilds the selected-layer filter');
  if (app.includes('/api/parcelquest')) failures.push('ParcelQuest must not be proxied');
  for (const feature of data.features || []) {
    if (!/^\d{3}-\d{3}-\d{3}$/.test(feature.properties?.APN || '')) failures.push(`invalid APN ${feature.properties?.APN}`);
    if ((!Array.isArray(feature.properties?.records) || !feature.properties.records.length) && (!Array.isArray(feature.properties?.salesHistory) || !feature.properties.salesHistory.length)) failures.push(`missing records for ${feature.properties?.APN}`);
  }
}
if (failures.length) { console.error(failures.map(item => `- ${item}`).join('\n')); process.exit(1); }
console.log('Passed: site files and parcel GeoJSON are valid.');
